"""2D polynomial evaluation and fitting.

Ported from polyval2.m and polyfitweighted2Subset.m.
"""

import math
import torch


def polyval2(p: torch.Tensor, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    """Evaluate 2D polynomial on a grid.

    MATLAB compatible: p is a flat vector of coefficients in the order
    generated by the Vandermonde construction (1, x, y, x^2, xy, y^2, ...).

    Returns:
        z: [ly, lx] shaped tensor
    """
    x = x.view(-1, 1)
    y = y.view(1, -1)

    lx = x.size(0)
    ly = y.size(1)
    lp = p.size(0)

    n = round((math.sqrt(1 + 8 * lp) - 3) / 2)

    x_grid = x.repeat(1, ly).view(-1)
    y_grid = y.repeat(lx, 1).view(-1)

    V = torch.ones(lx * ly, lp, device=p.device)
    ordercolumn = 1
    for order in range(1, int(n) + 1):
        for ordercolumn in range(ordercolumn, ordercolumn + order):
            V[:, ordercolumn] = x_grid * V[:, ordercolumn - order]
        ordercolumn += 1
        V[:, ordercolumn] = y_grid * V[:, ordercolumn - order - 1]

    z = torch.matmul(V, p.view(-1, 1))
    z = z.view(ly, lx)

    return z


def polyfit_weighted_2_subset(
    x_coords: torch.Tensor,
    y_coords: torch.Tensor,
    z_values: torch.Tensor,
    order: int,
    weights: torch.Tensor | None = None,
):
    """Fit a 2D polynomial to a subset of points with optional weights.

    Returns polynomial coefficients p such that polyval2(p, x, y) approximates z.
    """
    lx = len(x_coords)
    ly = len(y_coords)
    n_coeffs = (order + 1) * (order + 2) // 2

    x_grid = x_coords.view(-1, 1).repeat(1, ly).view(-1)
    y_grid = y_coords.view(1, -1).repeat(lx, 1).view(-1)
    z_flat = z_values.view(-1)

    V = torch.ones(lx * ly, n_coeffs, device=x_coords.device)
    col = 1
    for deg in range(1, order + 1):
        for c in range(col, col + deg):
            V[:, c] = x_grid * V[:, c - deg]
        col += 1
        V[:, col] = y_grid * V[:, col - deg - 1]

    if weights is not None:
        w = weights.view(-1)
        V = V * w.unsqueeze(1)
        z_flat = z_flat * w

    # Solve weighted least squares: V @ p = z
    p, _, _, _ = torch.linalg.lstsq(V, z_flat)
    return p
